### PR TITLE
Rewrote mappings sorter.

### PR DESCRIPTION
**Pull request by julienvincent**
Serve returns files based on the resolvedURL. Some things I changed:
- Base index referenced by `'/'`.
- Can serve indexes by globbing.
- Can map routes to static, or non (js | scss | html) files.

Working with tests.

### CODE REVIEW

**Comment by julienvincent** [comment]
Realized a bug where it isn't processing scss. Don't merge till I have fixed that.

**Comment by dylanvorster** [comment]
Also, static serving should actually be handled by the built in serve-static module inside express, thats why we didn't include this. In all my projects where Im using serve, i handle static files with serve-static @alexisvincent thoughts?

**Comment by alexisvincent** [comment]
Mapping to static files is different to static file system serving. @julienvincent Can you explain a bit more how your static implementation works and what it solves?

**Comment by alexisvincent** [comment]
How about we discuss this on the gitter channel

**Comment by julienvincent** [comment]
Any plan to merge this?

**Pull request merged**
